name: LuminaTestHarness
options:
  bundleIdPrefix: com.lumina.test
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    SWIFT_STRICT_CONCURRENCY: minimal

packages:
  LuminaVideoBridge:
    path: ../lumina-video-bridge

targets:
  LuminaTestHarness:
    type: application
    platform: iOS
    sources:
      - LuminaTestHarness
    dependencies:
      - package: LuminaVideoBridge
    info:
      path: LuminaTestHarness/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSLocalNetworkUsageDescription: "Connect to local MoQ relay for live video streaming"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lumina.test.harness
        DEVELOPMENT_TEAM: K6F7D9VUM7
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
        "LIBRARY_SEARCH_PATHS[sdk=iphoneos*]":
          - "$(SRCROOT)/../../target/aarch64-apple-ios/release"
        "LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*]":
          - "$(SRCROOT)/../../target/aarch64-apple-ios-sim/release"
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-lz"
          - "-liconv"
          - "-lbz2"
          - "-lc++"
